import * as THREE from './three.module.js';
import { GameMode } from '../classes/GameMode.class.js';
import { GameModeAR } from '../classes/GameModeAR.class.js';
import { World } from '../classes/World.class.js';
import { WorldAR } from '../classes/WorldAR.class.js';
export const TOWER_TYPE_DEFAULT = "TOWER_TYPE_DEFAULT";
export const TOWER_TYPE_ICE = "TOWER_TYPE_ICE";
export const TOWER_TYPE_FIRE = "TOWER_TYPE_FIRE";
export const TOWER_TYPE_SPEED = "TOWER_TYPE_SPEED";

export const GRASS_TILE = "GRASS_TILE";
export const GROUND_TILE = "GROUND_TILE";
export const CONCRETE_TILE = "CONCRETE_TILE";
export const EMPTY_TILE = "EMPTY_TILE";
export const SELECTED_TILE = "SELECTED_TILE";
export const HOVERED_TILE_OK = "HOVERED_TILE_OK";
export const HOVERED_TILE_ERR = "HOVERED_TILE_ERR";
export const GAME_MODE_DEFAULT = "GAME_MODE_DEFAULT";
export const GAME_MODE_AR = "GAME_MODE_AR";
export const DEFAULT_MATERIAL = new THREE.MeshBasicMaterial({ color: 0x03cafc } );

var tileMapConfig = [
		[
			{type: GRASS_TILE, interactive: true},
			{type: GRASS_TILE, interactive: true},
			{type: GRASS_TILE, interactive: true},
			{type: GRASS_TILE, interactive: true},
			{type: GRASS_TILE, interactive: true},
			{type: GRASS_TILE, interactive: true},
			{type: CONCRETE_TILE},
			{type: CONCRETE_TILE},
			{type: CONCRETE_TILE},
			{type: GRASS_TILE, interactive: true},
			{type: GRASS_TILE, interactive: true},
			{type: GRASS_TILE, interactive: true},
			{type: GRASS_TILE, interactive: true},
		],
		[
			{type: GRASS_TILE, interactive: true},
			{type: GRASS_TILE, interactive: true},
			{type: GRASS_TILE, interactive: true},
			{type: GRASS_TILE, interactive: true},
			{type: CONCRETE_TILE},
			{type: CONCRETE_TILE},
			{type: GRASS_TILE, interactive: true},
			{type: GRASS_TILE, interactive: true},
			{type: GRASS_TILE, interactive: true},
			{type: CONCRETE_TILE},
			{type: CONCRETE_TILE},
			{type: GRASS_TILE, interactive: true},
			{type: GRASS_TILE, interactive: true},
		],
		[
			{type: GRASS_TILE, interactive: true},
			{type: GRASS_TILE, interactive: true},
			{type: CONCRETE_TILE},
			{type: CONCRETE_TILE},
			{type: GRASS_TILE, interactive: true},
			{type: GRASS_TILE, interactive: true},
			{type: CONCRETE_TILE},
			{type: CONCRETE_TILE},
			{type: CONCRETE_TILE},
			{type: GRASS_TILE, interactive: true},
			{type: GRASS_TILE, interactive: true},
			{type: CONCRETE_TILE},
			{type: CONCRETE_TILE},
		],
		[
			{type: GRASS_TILE, interactive: true},
			{type: CONCRETE_TILE},
			{type: GRASS_TILE, interactive: true},
			{type: GRASS_TILE, interactive: true},
			{type: CONCRETE_TILE},
			{type: CONCRETE_TILE},
			{type: GRASS_TILE, interactive: true},
			{type: GRASS_TILE, interactive: true},
			{type: GRASS_TILE, interactive: true},
			{type: CONCRETE_TILE},
			{type: CONCRETE_TILE},
			{type: GRASS_TILE, interactive: true},
			{type: GRASS_TILE, interactive: true},
		],
		[
			{type: GRASS_TILE, interactive: true},
			{type: CONCRETE_TILE},
			{type: GRASS_TILE, interactive: true},
			{type: CONCRETE_TILE},
			{type: GRASS_TILE, interactive: true},
			{type: GRASS_TILE, interactive: true},
			{type: CONCRETE_TILE},
			{type: CONCRETE_TILE},
			{type: CONCRETE_TILE},
			{type: GRASS_TILE, interactive: true},
			{type: GRASS_TILE, interactive: true},
			{type: CONCRETE_TILE},
			{type: GRASS_TILE, interactive: true},
		],
		[
			{type: GRASS_TILE, interactive: true},
			{type: CONCRETE_TILE},
			{type: GRASS_TILE, interactive: true},
			{type: CONCRETE_TILE},
			{type: GRASS_TILE, interactive: true},
			{type: GRASS_TILE, interactive: true},
			{type: CONCRETE_TILE},
			{type: GRASS_TILE, interactive: true},
			{type: GRASS_TILE, interactive: true},
			{type: CONCRETE_TILE},
			{type: GRASS_TILE, interactive: true},
			{type: CONCRETE_TILE},
			{type: GRASS_TILE, interactive: true},
		],
		[
			{type: GRASS_TILE, interactive: true},
			{type: CONCRETE_TILE},
			{type: GRASS_TILE, interactive: true},
			{type: CONCRETE_TILE},
			{type: GRASS_TILE, interactive: true},
			{type: CONCRETE_TILE},
			{type: CONCRETE_TILE},
			{type: CONCRETE_TILE},
			{type: GRASS_TILE, interactive: true},
			{type: CONCRETE_TILE},
			{type: GRASS_TILE, interactive: true},
			{type: CONCRETE_TILE},
			{type: GRASS_TILE, interactive: true},
		],
		[
			{type: GRASS_TILE, interactive: true},
			{type: CONCRETE_TILE},
			{type: GRASS_TILE, interactive: true},
			{type: CONCRETE_TILE},
			{type: GRASS_TILE, interactive: true},
			{type: CONCRETE_TILE},
			{type: CONCRETE_TILE},
			{type: CONCRETE_TILE},
			{type: GRASS_TILE, interactive: true},
			{type: CONCRETE_TILE},
			{type: GRASS_TILE, interactive: true},
			{type: CONCRETE_TILE},
			{type: GRASS_TILE, interactive: true},
		],
		[
			{type: GRASS_TILE, interactive: true},
			{type: CONCRETE_TILE},
			{type: GRASS_TILE, interactive: true},
			{type: CONCRETE_TILE},
			{type: CONCRETE_TILE},
			{type: GRASS_TILE, interactive: true},
			{type: GRASS_TILE, interactive: true},
			{type: GRASS_TILE, interactive: true},
			{type: CONCRETE_TILE},
			{type: CONCRETE_TILE},
			{type: GRASS_TILE, interactive: true},
			{type: CONCRETE_TILE},
			{type: GRASS_TILE, interactive: true},
		],
		[
			{type: GRASS_TILE, interactive: true},
			{type: CONCRETE_TILE},
			{type: CONCRETE_TILE},
			{type: GRASS_TILE, interactive: true},
			{type: GRASS_TILE, interactive: true},
			{type: CONCRETE_TILE},
			{type: CONCRETE_TILE},
			{type: CONCRETE_TILE},
			{type: GRASS_TILE, interactive: true},
			{type: GRASS_TILE, interactive: true},
			{type: CONCRETE_TILE},
			{type: CONCRETE_TILE},
			{type: GRASS_TILE, interactive: true},
		],
		[
			{type: GRASS_TILE, interactive: true},
			{type: GRASS_TILE, interactive: true},
			{type: GRASS_TILE, interactive: true},
			{type: CONCRETE_TILE},
			{type: CONCRETE_TILE},
			{type: GRASS_TILE, interactive: true},
			{type: GRASS_TILE, interactive: true},
			{type: GRASS_TILE, interactive: true},
			{type: CONCRETE_TILE},
			{type: CONCRETE_TILE},
			{type: GRASS_TILE, interactive: true},
			{type: GRASS_TILE, interactive: true},
			{type: GRASS_TILE, interactive: true},
		],
		[
			{type: GRASS_TILE, interactive: true},
			{type: GRASS_TILE, interactive: true},
			{type: GRASS_TILE, interactive: true},
			{type: GRASS_TILE, interactive: true},
			{type: GRASS_TILE, interactive: true},
			{type: CONCRETE_TILE},
			{type: CONCRETE_TILE},
			{type: CONCRETE_TILE},
			{type: GRASS_TILE, interactive: true},
			{type: GRASS_TILE, interactive: true},
			{type: GRASS_TILE, interactive: true},
			{type: GRASS_TILE, interactive: true},
			{type: GRASS_TILE, interactive: true},
		],
		[
			{type: GRASS_TILE, interactive: true},
			{type: GRASS_TILE, interactive: true},
			{type: GRASS_TILE, interactive: true},
			{type: GRASS_TILE, interactive: true},
			{type: GRASS_TILE, interactive: true},
			{type: GRASS_TILE, interactive: true},
			{type: GRASS_TILE, interactive: true},
			{type: GRASS_TILE, interactive: true},
			{type: GRASS_TILE, interactive: true},
			{type: GRASS_TILE, interactive: true},
			{type: GRASS_TILE, interactive: true},
			{type: GRASS_TILE, interactive: true},
			{type: GRASS_TILE, interactive: true},
		],
	];	

var newMapConfig = [
		[
			{type: GRASS_TILE, interactive: true},
			{type: GRASS_TILE, interactive: true},
			{type: GRASS_TILE, interactive: true},
			{type: GRASS_TILE, interactive: true},
			{type: GRASS_TILE, interactive: true},
			{type: GRASS_TILE, interactive: true},
			{type: CONCRETE_TILE},
			{type: CONCRETE_TILE},
			{type: CONCRETE_TILE},
			{type: GRASS_TILE, interactive: true},
			{type: GRASS_TILE, interactive: true},
			{type: GRASS_TILE, interactive: true},
			{type: GRASS_TILE, interactive: true},
		],
		[
			{type: GRASS_TILE, interactive: true},
			{type: GRASS_TILE, interactive: true},
			{type: GRASS_TILE, interactive: true},
			{type: GRASS_TILE, interactive: true},
			{type: CONCRETE_TILE},
			{type: CONCRETE_TILE},
			{type: GRASS_TILE, interactive: true},
			{type: GRASS_TILE, interactive: true},
			{type: GRASS_TILE, interactive: true},
			{type: CONCRETE_TILE},
			{type: CONCRETE_TILE},
			{type: GRASS_TILE, interactive: true},
			{type: GRASS_TILE, interactive: true},
		],
		[
			{type: GRASS_TILE, interactive: true},
			{type: GRASS_TILE, interactive: true},
			{type: CONCRETE_TILE},
			{type: CONCRETE_TILE},
			{type: GRASS_TILE, interactive: true},
			{type: GRASS_TILE, interactive: true},
			{type: CONCRETE_TILE},
			{type: CONCRETE_TILE},
			{type: CONCRETE_TILE},
			{type: GRASS_TILE, interactive: true},
			{type: GRASS_TILE, interactive: true},
			{type: CONCRETE_TILE},
			{type: CONCRETE_TILE},
		],
		[
			{type: GRASS_TILE, interactive: true},
			{type: CONCRETE_TILE},
			{type: GRASS_TILE, interactive: true},
			{type: GRASS_TILE, interactive: true},
			{type: CONCRETE_TILE},
			{type: CONCRETE_TILE},
			{type: GRASS_TILE, interactive: true},
			{type: GRASS_TILE, interactive: true},
			{type: GRASS_TILE, interactive: true},
			{type: CONCRETE_TILE},
			{type: CONCRETE_TILE},
			{type: GRASS_TILE, interactive: true},
			{type: GRASS_TILE, interactive: true},
		],
		[
			{type: GRASS_TILE, interactive: true},
			{type: CONCRETE_TILE},
			{type: GRASS_TILE, interactive: true},
			{type: CONCRETE_TILE},
			{type: GRASS_TILE, interactive: true},
			{type: GRASS_TILE, interactive: true},
			{type: CONCRETE_TILE},
			{type: CONCRETE_TILE},
			{type: CONCRETE_TILE},
			{type: GRASS_TILE, interactive: true},
			{type: GRASS_TILE, interactive: true},
			{type: CONCRETE_TILE},
			{type: GRASS_TILE, interactive: true},
		],
		[
			{type: GRASS_TILE, interactive: true},
			{type: CONCRETE_TILE},
			{type: GRASS_TILE, interactive: true},
			{type: CONCRETE_TILE},
			{type: GRASS_TILE, interactive: true},
			{type: GRASS_TILE, interactive: true},
			{type: CONCRETE_TILE},
			{type: GRASS_TILE, interactive: true},
			{type: GRASS_TILE, interactive: true},
			{type: CONCRETE_TILE},
			{type: GRASS_TILE, interactive: true},
			{type: CONCRETE_TILE},
			{type: GRASS_TILE, interactive: true},
		],
		[
			{type: GRASS_TILE, interactive: true},
			{type: CONCRETE_TILE},
			{type: GRASS_TILE, interactive: true},
			{type: CONCRETE_TILE},
			{type: GRASS_TILE, interactive: true},
			{type: CONCRETE_TILE},
			{type: CONCRETE_TILE},
			{type: CONCRETE_TILE},
			{type: GRASS_TILE, interactive: true},
			{type: CONCRETE_TILE},
			{type: GRASS_TILE, interactive: true},
			{type: CONCRETE_TILE},
			{type: GRASS_TILE, interactive: true},
		],
		[
			{type: GRASS_TILE, interactive: true},
			{type: CONCRETE_TILE},
			{type: GRASS_TILE, interactive: true},
			{type: CONCRETE_TILE},
			{type: GRASS_TILE, interactive: true},
			{type: CONCRETE_TILE},
			{type: CONCRETE_TILE},
			{type: CONCRETE_TILE},
			{type: GRASS_TILE, interactive: true},
			{type: CONCRETE_TILE},
			{type: GRASS_TILE, interactive: true},
			{type: CONCRETE_TILE},
			{type: GRASS_TILE, interactive: true},
		],
		[
			{type: GRASS_TILE, interactive: true},
			{type: CONCRETE_TILE},
			{type: GRASS_TILE, interactive: true},
			{type: CONCRETE_TILE},
			{type: CONCRETE_TILE},
			{type: GRASS_TILE, interactive: true},
			{type: GRASS_TILE, interactive: true},
			{type: GRASS_TILE, interactive: true},
			{type: CONCRETE_TILE},
			{type: CONCRETE_TILE},
			{type: GRASS_TILE, interactive: true},
			{type: CONCRETE_TILE},
			{type: GRASS_TILE, interactive: true},
		],
		[
			{type: GRASS_TILE, interactive: true},
			{type: CONCRETE_TILE},
			{type: CONCRETE_TILE},
			{type: GRASS_TILE, interactive: true},
			{type: GRASS_TILE, interactive: true},
			{type: CONCRETE_TILE},
			{type: CONCRETE_TILE},
			{type: CONCRETE_TILE},
			{type: GRASS_TILE, interactive: true},
			{type: GRASS_TILE, interactive: true},
			{type: CONCRETE_TILE},
			{type: CONCRETE_TILE},
			{type: GRASS_TILE, interactive: true},
		],
		[
			{type: GRASS_TILE, interactive: true},
			{type: GRASS_TILE, interactive: true},
			{type: GRASS_TILE, interactive: true},
			{type: CONCRETE_TILE},
			{type: CONCRETE_TILE},
			{type: GRASS_TILE, interactive: true},
			{type: GRASS_TILE, interactive: true},
			{type: GRASS_TILE, interactive: true},
			{type: CONCRETE_TILE},
			{type: CONCRETE_TILE},
			{type: GRASS_TILE, interactive: true},
			{type: GRASS_TILE, interactive: true},
			{type: GRASS_TILE, interactive: true},
		],
		[
			{type: GRASS_TILE, interactive: true},
			{type: GRASS_TILE, interactive: true},
			{type: GRASS_TILE, interactive: true},
			{type: GRASS_TILE, interactive: true},
			{type: GRASS_TILE, interactive: true},
			{type: CONCRETE_TILE},
			{type: CONCRETE_TILE},
			{type: CONCRETE_TILE},
			{type: GRASS_TILE, interactive: true},
			{type: GRASS_TILE, interactive: true},
			{type: GRASS_TILE, interactive: true},
			{type: GRASS_TILE, interactive: true},
			{type: GRASS_TILE, interactive: true},
		],
		[
			{type: GRASS_TILE, interactive: true},
			{type: GRASS_TILE, interactive: true},
			{type: GRASS_TILE, interactive: true},
			{type: GRASS_TILE, interactive: true},
			{type: GRASS_TILE, interactive: true},
			{type: GRASS_TILE, interactive: true},
			{type: GRASS_TILE, interactive: true},
			{type: GRASS_TILE, interactive: true},
			{type: GRASS_TILE, interactive: true},
			{type: GRASS_TILE, interactive: true},
			{type: GRASS_TILE, interactive: true},
			{type: GRASS_TILE, interactive: true},
			{type: GRASS_TILE, interactive: true},
		],
	];	

var tileSize = 0.4;
var tileMapConfigLength = tileMapConfig.length;
export const DEFAULT_MAP_AR = {
	tileMapConfig: tileMapConfig,
	startPoint: {column: 0, row: 2},
	endPoint: {column: 0, row: 6},
	enemyPath: [{c: 11, r: 2}, {c: 10, r: 1}, {c: 9, r: 1}, {c: 8, r: 0}, {c: 7, r: 0},
				{c: 6, r: 0}, {c: 5, r: 1}, {c: 4, r: 1}, {c: 3, r: 2}, {c: 2, r: 2},
				{c: 1, r: 3}, {c: 1, r: 4}, {c: 1, r: 5}, {c: 1, r: 6}, {c: 1, r: 7},
				{c: 1, r: 8}, {c: 1, r: 9}, {c: 2, r: 9}, {c: 3, r: 10}, {c: 4, r: 10},
				{c: 5, r: 11}, {c: 6, r: 11}, {c: 7, r: 11}, {c: 8, r: 10}, {c: 9, r: 10},
				{c: 10, r: 9}, {c: 11, r: 9}, {c: 11, r: 8}, {c: 11, r: 7}, {c: 11, r: 6},
				{c: 11, r: 5}, {c: 11, r: 4}, {c: 10, r: 3}, {c: 9, r: 3}, {c: 8, r: 2},
				{c: 7, r: 2}, {c: 6, r: 2}, {c: 5, r: 3}, {c: 4, r: 3}, {c: 3, r: 4},
				{c: 3, r: 5}, {c: 3, r: 6}, {c: 3, r: 7}, {c: 3, r: 8}, {c: 4, r: 8},
				{c: 5, r: 9}, {c: 7, r: 9}, {c: 8, r: 8}, {c: 9, r: 8}, {c: 9, r: 7},
				{c: 9, r: 6}, {c: 9, r: 5}, {c: 8, r: 4}, {c: 7, r: 4}, {c: 6, r: 4},
				{c: 6, r: 5}, {c: 6, r: 6},
				],
	tileSize: tileSize,
	tileOffsetX: tileMapConfig[parseInt(tileMapConfigLength / 2)].length * tileSize,
	tileOffsetY: tileMapConfigLength * tileSize
}

tileSize = 2;
export const DEFAULT_MAP = {
	tileMapConfig: newMapConfig,
	startPoint: {column: 12, row: 2},
	endPoint: {column: 6, row: 6},
	enemyPath: [{c: 11, r: 2}, {c: 10, r: 1}, {c: 9, r: 1}, {c: 8, r: 0}, {c: 7, r: 0},
				{c: 6, r: 0}, {c: 5, r: 1}, {c: 4, r: 1}, {c: 3, r: 2}, {c: 2, r: 2},
				{c: 1, r: 3}, {c: 1, r: 4}, {c: 1, r: 5}, {c: 1, r: 6}, {c: 1, r: 7},
				{c: 1, r: 8}, {c: 1, r: 9}, {c: 2, r: 9}, {c: 3, r: 10}, {c: 4, r: 10},
				{c: 5, r: 11}, {c: 6, r: 11}, {c: 7, r: 11}, {c: 8, r: 10}, {c: 9, r: 10},
				{c: 10, r: 9}, {c: 11, r: 9}, {c: 11, r: 8}, {c: 11, r: 7}, {c: 11, r: 6},
				{c: 11, r: 5}, {c: 11, r: 4}, {c: 10, r: 3}, {c: 9, r: 3}, {c: 8, r: 2},
				{c: 7, r: 2}, {c: 6, r: 2}, {c: 5, r: 3}, {c: 4, r: 3}, {c: 3, r: 4},
				{c: 3, r: 5}, {c: 3, r: 6}, {c: 3, r: 7}, {c: 3, r: 8}, {c: 4, r: 8},
				{c: 5, r: 9}, {c: 7, r: 9}, {c: 8, r: 8}, {c: 9, r: 8}, {c: 9, r: 7},
				{c: 9, r: 6}, {c: 9, r: 5}, {c: 8, r: 4}, {c: 7, r: 4}, {c: 6, r: 4},
				{c: 6, r: 5}, {c: 6, r: 6},
				],
	tileSize: tileSize,
	tileOffsetX:0,
	tileOffsetY: 0
}



export const GAME_MODES = {
	GAME_MODE_DEFAULT: GameMode,
	GAME_MODE_AR: GameModeAR,
}

export const WORLD_MODES = {
	GAME_MODE_DEFAULT: World,
	GAME_MODE_AR: WorldAR,
}
export const MAP_MODES = {
	GAME_MODE_DEFAULT: DEFAULT_MAP,
	GAME_MODE_AR: DEFAULT_MAP_AR,
}

export const TOWER_SETTINGS = [
	{
		type: TOWER_TYPE_ICE,
		price: 20,
		damage: 30,
		range: 1,
		attack_speed: 1,
		HOVERED_TILE_OK,
		name: "Ice Tower",
	},
	{
		type: TOWER_TYPE_FIRE,
		price: 30,
		damage: 60,
		range: 1,
		attack_speed: 2,
		material:HOVERED_TILE_ERR,
		name: "Fire Tower",
	},
	{
		type: TOWER_TYPE_SPEED,
		price: 50,
		range: 2,
		damage: 25,
		attack_speed: 0.5,
		material: GROUND_TILE,
		name: "Speed Tower",
	}
]


export const PLAYER_SETTINGS = {
	gold: 200,
	lives: 20,
	time_between_hordes: 20,
	tower_settings:	TOWER_SETTINGS,
};